### PR TITLE
QOL Updates

### PR DESCRIPTION
**Pull request by kryptone**
Few small feature updates;

- support for standalone so steam does not boot on game load
- ability to patch hosts file to block communication with game API
- application only runs if user has admin privilege 
- small typo fix

### CODE REVIEW

**Comment by kryptone** [comment]
apologies for bad diff and any bad characters that may have found there way in, i edited code via github website

**Comment by dumpsters** [comment]
> application only runs if user has admin privilege

Why? game runs fine without admin privileges. Why not ask for elevation if you want to modify hosts or system files

**Comment by uberhalit** [comment]
Hello, I totally missed your PR today, I am terrible sorry. I've added an admin-check already. About the host-file modification I'd rather not do that as some AntiVirus (Kasperksy) have had issues with these in the past and flaged apps as malicious. Steam on the other hand is a good idea. Do you see a way to automatically detect if steam is neccessary or not? I'd like to automatically decide about start-up in the background instead.

**Comment by kryptone** [comment]
not a problem! :) I believe what you are looking for is contained within these files;

SteamLibrary/steamapps/appmanifest_*.acf

there should be a list of all the steam 'appid' & 'installdir' that are currently actively installed on the system.

unfortunately, you may find difficultly in determining the correct the location of the SteamLibrary. If a 'user' has installed games on multiple disks for example, they will have *multiple* SteamLibrary folders all with similar file/folder structure. You can check this behaviour by moving your elden ring install to a different disk.

**Comment by Erengis** [comment]
Hey man, greatly appreciate you making this mod so early! What I loved in your Sekiro mod was the ability to "disable camera auto rotate adjustment on movement". It is desperately needed here as well for horse combat with KB+M. Cheers!

**Pull request closed without merging**
