### PR TITLE
fix CompilerService reference, add icon, include required System DLL's

### PR DESCRIPTION
**Pull request by DubbleClick**

### CODE REVIEW

**Comment by DubbleClick** [comment]
tackles #2 (and #8 )

**Comment by uberhalit** [comment]
Hi, thank you for your contribution. I've removed all unneccessary references. Didn't realize that Unsafe requires external DLLs on .NET 4.8. It is part of the framework itself on .NET 6.

For the Icon we have to concider CopyRights, I am going to add the old one as I have written permisson to use that.

**Comment by DubbleClick** [comment]
Hey, yeah that sounds like a good idea, unfortunately .ico was sneakily added to the gitignore so your icon resource didn't make it to github.

**Comment by DubbleClick** [comment]
considering the dependency on compilerservices.unsafe isn't even required anymore, this PR can safely be closed. please upload the icon though still :)

**Comment by uberhalit** [comment]
> Hey, yeah that sounds like a good idea, unfortunately .ico was sneakily added to the gitignore so your icon resource didn't make it to github.

That's on purpose, I am not allowed to share the icon itself, only bundled into an app.

**Pull request closed without merging**
